services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pesquisaaqui
      POSTGRES_PASSWORD: pesquisaaqui
      POSTGRES_DB: pesquisaaqui
    volumes:
      - pesquisa_aqui_pg:/var/lib/postgresql/data

volumes:
  pesquisa_aqui_pg:
